export default {
  displayName: 'Hashbrown',
  name: 'hashbrown',
  type: 'dark' as const,
  colors: {
    'activityBar.activeBorder': '#f78166',
    'activityBar.background': '#3D3C3A',
    'activityBar.border': '#3D3C3A',
    'activityBar.foreground': '#FAF9F0',
    'activityBar.inactiveForeground': '#A4A3A1',
    'activityBarBadge.background': '#1f6feb',
    'activityBarBadge.foreground': '#FAF9F0',
    'badge.background': '#1f6feb',
    'badge.foreground': '#FAF9F0',
    'breadcrumb.activeSelectionForeground': '#A4A3A1',
    'breadcrumb.focusForeground': '#FAF9F0',
    'breadcrumb.foreground': '#A4A3A1',
    'breadcrumbPicker.background': '#5E5C5A',
    'button.background': '#616F36',
    'button.foreground': '#FAF9F0',
    'button.hoverBackground': '#A0A985',
    'button.secondaryBackground': '#5E5C5A',
    'button.secondaryForeground': '#D8ECEF',
    'button.secondaryHoverBackground': '#3D3C3A',
    'checkbox.background': '#5E5C5A',
    'checkbox.border': '#3D3C3A',
    'debugConsole.errorForeground': '#774625',
    'debugConsole.infoForeground': '#A4A3A1',
    'debugConsole.sourceForeground': '#E88C4D',
    'debugConsole.warningForeground': '#E88C4D',
    'debugConsoleInputIcon.foreground': '#D8ECEF',
    'debugIcon.breakpointForeground': '#774625',
    'debugTokenExpression.boolean': '#A0A985',
    'debugTokenExpression.error': '#774625',
    'debugTokenExpression.name': '#64AFB5',
    'debugTokenExpression.number': '#A0A985',
    'debugTokenExpression.string': '#9ECFD7',
    'debugTokenExpression.value': '#9ECFD7',
    'debugToolBar.background': '#5E5C5A',
    descriptionForeground: '#A4A3A1',
    'diffEditor.insertedLineBackground': '#616F3626',
    'diffEditor.insertedTextBackground': '#A0A9854d',
    'diffEditor.removedLineBackground': '#da363326',
    'diffEditor.removedTextBackground': '#E8A23D4d',
    'dropdown.background': '#5E5C5A',
    'dropdown.border': '#3D3C3A',
    'dropdown.foreground': '#FAF9F0',
    'dropdown.listBackground': '#5E5C5A',
    'editor.background': 'transparent',
    'editor.findMatchBackground': '#774625',
    'editor.findMatchHighlightBackground': '#FBBB5280',
    'editor.focusedStackFrameHighlightBackground': '#A0A98566',
    'editor.foldBackground': '#A4A3A11a',
    'editor.foreground': '#FAF9F0',
    'editor.lineHighlightBackground': '#A4A3A11a',
    'editor.linkedEditingBackground': '#64AFB512',
    'editor.selectionHighlightBackground': '#A0A98540',
    'editor.stackFrameHighlightBackground': '#bb800966',
    'editor.wordHighlightBackground': '#A4A3A180',
    'editor.wordHighlightBorder': '#A4A3A199',
    'editor.wordHighlightStrongBackground': '#A4A3A14d',
    'editor.wordHighlightStrongBorder': '#A4A3A199',
    'editorBracketHighlight.foreground1': '#64AFB5',
    'editorBracketHighlight.foreground2': '#A0A985',
    'editorBracketHighlight.foreground3': '#E88C4D',
    'editorBracketHighlight.foreground4': '#774625',
    'editorBracketHighlight.foreground5': '#F6D1B8',
    'editorBracketHighlight.foreground6': '#F6D1B8',
    'editorBracketHighlight.unexpectedBracket.foreground': '#A4A3A1',
    'editorBracketMatch.background': '#A0A98540',
    'editorBracketMatch.border': '#A0A98599',
    'editorCursor.foreground': '#64AFB5',
    'editorGroup.border': '#3D3C3A',
    'editorGroupHeader.tabsBackground': '#3D3C3A',
    'editorGroupHeader.tabsBorder': '#3D3C3A',
    'editorGutter.addedBackground': '#A0A98566',
    'editorGutter.deletedBackground': '#77462566',
    'editorGutter.modifiedBackground': '#bb800966',
    'editorIndentGuide.activeBackground': '#FAF9F03d',
    'editorIndentGuide.background': '#FAF9F01f',
    'editorInlayHint.background': '#A4A3A133',
    'editorInlayHint.foreground': '#A4A3A1',
    'editorInlayHint.paramBackground': '#A4A3A133',
    'editorInlayHint.paramForeground': '#A4A3A1',
    'editorInlayHint.typeBackground': '#A4A3A133',
    'editorInlayHint.typeForeground': '#A4A3A1',
    'editorLineNumber.activeForeground': '#FAF9F0',
    'editorLineNumber.foreground': '#A4A3A1',
    'editorOverviewRuler.border': '#3D3C3A',
    'editorWhitespace.foreground': '#A4A3A1',
    'editorWidget.background': '#5E5C5A',
    errorForeground: '#774625',
    focusBorder: '#1f6feb',
    foreground: '#FAF9F0',
    'gitDecoration.addedResourceForeground': '#A0A985',
    'gitDecoration.conflictingResourceForeground': '#db6d28',
    'gitDecoration.deletedResourceForeground': '#774625',
    'gitDecoration.ignoredResourceForeground': '#A4A3A1',
    'gitDecoration.modifiedResourceForeground': '#E88C4D',
    'gitDecoration.submoduleResourceForeground': '#A4A3A1',
    'gitDecoration.untrackedResourceForeground': '#A0A985',
    'icon.foreground': '#A4A3A1',
    'input.background': '#3D3C3A',
    'input.border': '#3D3C3A',
    'input.foreground': '#FAF9F0',
    'input.placeholderForeground': '#A4A3A1',
    'keybindingLabel.foreground': '#FAF9F0',
    'list.activeSelectionBackground': '#A4A3A166',
    'list.activeSelectionForeground': '#FAF9F0',
    'list.focusBackground': '#388bfd26',
    'list.focusForeground': '#FAF9F0',
    'list.highlightForeground': '#64AFB5',
    'list.hoverBackground': '#A4A3A11a',
    'list.hoverForeground': '#FAF9F0',
    'list.inactiveFocusBackground': '#388bfd26',
    'list.inactiveSelectionBackground': '#A4A3A166',
    'list.inactiveSelectionForeground': '#FAF9F0',
    'minimapSlider.activeBackground': '#A4A3A147',
    'minimapSlider.background': '#A4A3A133',
    'minimapSlider.hoverBackground': '#A4A3A13d',
    'notificationCenterHeader.background': '#5E5C5A',
    'notificationCenterHeader.foreground': '#A4A3A1',
    'notifications.background': '#5E5C5A',
    'notifications.border': '#3D3C3A',
    'notifications.foreground': '#FAF9F0',
    'notificationsErrorIcon.foreground': '#774625',
    'notificationsInfoIcon.foreground': '#64AFB5',
    'notificationsWarningIcon.foreground': '#E88C4D',
    'panel.background': '#3D3C3A',
    'panel.border': '#3D3C3A',
    'panelInput.border': '#3D3C3A',
    'panelTitle.activeBorder': '#f78166',
    'panelTitle.activeForeground': '#FAF9F0',
    'panelTitle.inactiveForeground': '#A4A3A1',
    'peekViewEditor.background': '#A4A3A11a',
    'peekViewEditor.matchHighlightBackground': '#bb800966',
    'peekViewResult.background': '#3D3C3A',
    'peekViewResult.matchHighlightBackground': '#bb800966',
    'pickerGroup.border': '#3D3C3A',
    'pickerGroup.foreground': '#A4A3A1',
    'progressBar.background': '#1f6feb',
    'quickInput.background': '#5E5C5A',
    'quickInput.foreground': '#FAF9F0',
    'scrollbar.shadow': '#A4A3A133',
    'scrollbarSlider.activeBackground': '#A4A3A147',
    'scrollbarSlider.background': '#A4A3A133',
    'scrollbarSlider.hoverBackground': '#A4A3A13d',
    'settings.headerForeground': '#FAF9F0',
    'settings.modifiedItemIndicator': '#bb800966',
    'sideBar.background': '#3D3C3A',
    'sideBar.border': '#3D3C3A',
    'sideBar.foreground': '#FAF9F0',
    'sideBarSectionHeader.background': '#3D3C3A',
    'sideBarSectionHeader.border': '#3D3C3A',
    'sideBarSectionHeader.foreground': '#FAF9F0',
    'sideBarTitle.foreground': '#FAF9F0',
    'statusBar.background': '#3D3C3A',
    'statusBar.border': '#3D3C3A',
    'statusBar.debuggingBackground': '#da3633',
    'statusBar.debuggingForeground': '#FAF9F0',
    'statusBar.focusBorder': '#1f6feb80',
    'statusBar.foreground': '#A4A3A1',
    'statusBar.noFolderBackground': '#3D3C3A',
    'statusBarItem.activeBackground': '#FAF9F01f',
    'statusBarItem.focusBorder': '#1f6feb',
    'statusBarItem.hoverBackground': '#FAF9F014',
    'statusBarItem.prominentBackground': '#A4A3A166',
    'statusBarItem.remoteBackground': '#3D3C3A',
    'statusBarItem.remoteForeground': '#FAF9F0',
    'symbolIcon.arrayForeground': '#f0883e',
    'symbolIcon.booleanForeground': '#64AFB5',
    'symbolIcon.classForeground': '#f0883e',
    'symbolIcon.colorForeground': '#64AFB5',
    'symbolIcon.constantForeground': [
      '#aff5b4',
      '#7ee787',
      '#A0A985',
      '#A0A985',
      '#A0A985',
      '#616F36',
      '#196c2e',
      '#0f5323',
      '#033a16',
      '#04260f',
    ],
    'symbolIcon.constructorForeground': '#F6D1B8',
    'symbolIcon.enumeratorForeground': '#f0883e',
    'symbolIcon.enumeratorMemberForeground': '#64AFB5',
    'symbolIcon.eventForeground': '#A4A3A1',
    'symbolIcon.fieldForeground': '#f0883e',
    'symbolIcon.fileForeground': '#E88C4D',
    'symbolIcon.folderForeground': '#E88C4D',
    'symbolIcon.functionForeground': '#D8ECEF',
    'symbolIcon.interfaceForeground': '#f0883e',
    'symbolIcon.keyForeground': '#64AFB5',
    'symbolIcon.keywordForeground': '#E8A23D',
    'symbolIcon.methodForeground': '#D8ECEF',
    'symbolIcon.moduleForeground': '#E8A23D',
    'symbolIcon.namespaceForeground': '#E8A23D',
    'symbolIcon.nullForeground': '#64AFB5',
    'symbolIcon.numberForeground': '#A0A985',
    'symbolIcon.objectForeground': '#f0883e',
    'symbolIcon.operatorForeground': '#64AFB5',
    'symbolIcon.packageForeground': '#f0883e',
    'symbolIcon.propertyForeground': '#f0883e',
    'symbolIcon.referenceForeground': '#64AFB5',
    'symbolIcon.snippetForeground': '#64AFB5',
    'symbolIcon.stringForeground': '#64AFB5',
    'symbolIcon.structForeground': '#f0883e',
    'symbolIcon.textForeground': '#64AFB5',
    'symbolIcon.typeParameterForeground': '#64AFB5',
    'symbolIcon.unitForeground': '#64AFB5',
    'symbolIcon.variableForeground': '#f0883e',
    'tab.activeBackground': '#3D3C3A',
    'tab.activeBorder': '#3D3C3A',
    'tab.activeBorderTop': '#f78166',
    'tab.activeForeground': '#FAF9F0',
    'tab.border': '#3D3C3A',
    'tab.hoverBackground': '#3D3C3A',
    'tab.inactiveBackground': '#3D3C3A',
    'tab.inactiveForeground': '#A4A3A1',
    'tab.unfocusedActiveBorder': '#3D3C3A',
    'tab.unfocusedActiveBorderTop': '#3D3C3A',
    'tab.unfocusedHoverBackground': '#A4A3A11a',
    'terminal.ansiBlack': '#A4A3A1',
    'terminal.ansiBlue': '#64AFB5',
    'terminal.ansiBrightBlack': '#A4A3A1',
    'terminal.ansiBrightBlue': '#64AFB5',
    'terminal.ansiBrightCyan': '#9ECFD7',
    'terminal.ansiBrightGreen': '#A0A985',
    'terminal.ansiBrightMagenta': '#F6D1B8',
    'terminal.ansiBrightRed': '#774625',
    'terminal.ansiBrightWhite': '#FAF9F0',
    'terminal.ansiBrightYellow': '#E88C4D',
    'terminal.ansiCyan': '#9ECFD7',
    'terminal.ansiGreen': '#A0A985',
    'terminal.ansiMagenta': '#D8ECEF',
    'terminal.ansiRed': '#E8A23D',
    'terminal.ansiWhite': '#b1bac4',
    'terminal.ansiYellow': '#E88C4D',
    'terminal.foreground': '#FAF9F0',
    'textBlockQuote.background': '#3D3C3A',
    'textBlockQuote.border': '#3D3C3A',
    'textCodeBlock.background': '#A4A3A166',
    'textLink.activeForeground': '#64AFB5',
    'textLink.foreground': '#64AFB5',
    'textPreformat.background': '#A4A3A166',
    'textPreformat.foreground': '#A4A3A1',
    'textSeparator.foreground': '#5E5C5A',
    'titleBar.activeBackground': '#3D3C3A',
    'titleBar.activeForeground': '#A4A3A1',
    'titleBar.border': '#3D3C3A',
    'titleBar.inactiveBackground': '#3D3C3A',
    'titleBar.inactiveForeground': '#A4A3A1',
    'tree.indentGuidesStroke': '#5E5C5A',
    'welcomePage.buttonBackground': '#5E5C5A',
    'welcomePage.buttonHoverBackground': '#3D3C3A',
  },
  settings: [
    {
      scope: ['comment', 'punctuation.definition.comment', 'string.comment'],
      settings: {
        foreground: '#A4A3A1',
      },
    },
    {
      scope: ['constant.other.placeholder', 'constant.character'],
      settings: {
        foreground: '#E8A23D',
      },
    },
    {
      scope: [
        'constant',
        'entity.name.constant',
        'variable.other.constant',
        'variable.other.enummember',
        'variable.language',
        'entity',
      ],
      settings: {
        foreground: '#64AFB5',
      },
    },
    {
      scope: ['entity.name'],
      settings: {
        foreground: '#ffa657',
      },
    },
    {
      scope: ['meta.export.default'],
      settings: {
        foreground: '#FBBB52',
      },
    },
    {
      scope: ['meta.definition.variable'],
      settings: {
        foreground: '#ffa657',
      },
    },
    {
      scope: [
        'variable.parameter.function',
        'meta.jsx.children',
        'meta.block',
        'meta.tag.attributes',
        'entity.name.constant',
        'meta.object.member',
        'meta.embedded.expression',
      ],
      settings: {
        foreground: '#FAF9F0',
      },
    },
    {
      scope: 'entity.name.function',
      settings: {
        foreground: '#F6D1B8',
      },
    },
    {
      scope: ['entity.name.tag', 'support.class.component'],
      settings: {
        foreground: '#7ee787',
      },
    },
    {
      scope: 'keyword',
      settings: {
        foreground: '#E8A23D',
      },
    },
    {
      scope: ['storage', 'storage.type'],
      settings: {
        foreground: '#E8A23D',
      },
    },
    {
      scope: [
        'storage.modifier.package',
        'storage.modifier.import',
        'storage.type.java',
      ],
      settings: {
        foreground: '#FAF9F0',
      },
    },
    {
      scope: ['string', 'string punctuation.section.embedded source'],
      settings: {
        foreground: '#9ECFD7',
      },
    },
    {
      scope: 'support',
      settings: {
        foreground: '#64AFB5',
      },
    },
    {
      scope: 'meta.property-name',
      settings: {
        foreground: '#64AFB5',
      },
    },
    {
      scope: 'variable',
      settings: {
        foreground: '#ffa657',
      },
    },
    {
      scope: 'variable.other',
      settings: {
        foreground: '#FAF9F0',
      },
    },
    {
      scope: 'invalid.broken',
      settings: {
        fontStyle: 'italic',
        foreground: '#774625',
      },
    },
    {
      scope: 'invalid.deprecated',
      settings: {
        fontStyle: 'italic',
        foreground: '#774625',
      },
    },
    {
      scope: 'invalid.illegal',
      settings: {
        fontStyle: 'italic',
        foreground: '#774625',
      },
    },
    {
      scope: 'invalid.unimplemented',
      settings: {
        fontStyle: 'italic',
        foreground: '#774625',
      },
    },
    {
      scope: 'carriage-return',
      settings: {
        background: '#E8A23D',
        content: '^M',
        fontStyle: 'italic underline',
        foreground: '#f0f6fc',
      },
    },
    {
      scope: 'message.error',
      settings: {
        foreground: '#774625',
      },
    },
    {
      scope: 'string variable',
      settings: {
        foreground: '#64AFB5',
      },
    },
    {
      scope: ['source.regexp', 'string.regexp'],
      settings: {
        foreground: '#9ECFD7',
      },
    },
    {
      scope: [
        'string.regexp.character-class',
        'string.regexp constant.character.escape',
        'string.regexp source.ruby.embedded',
        'string.regexp string.regexp.arbitrary-repitition',
      ],
      settings: {
        foreground: '#9ECFD7',
      },
    },
    {
      scope: 'string.regexp constant.character.escape',
      settings: {
        fontStyle: 'bold',
        foreground: '#7ee787',
      },
    },
    {
      scope: 'support.constant',
      settings: {
        foreground: '#64AFB5',
      },
    },
    {
      scope: 'support.variable',
      settings: {
        foreground: '#64AFB5',
      },
    },
    {
      scope: 'support.type.property-name.json',
      settings: {
        foreground: '#7ee787',
      },
    },
    {
      scope: 'meta.module-reference',
      settings: {
        foreground: '#64AFB5',
      },
    },
    {
      scope: 'punctuation.definition.list.begin.markdown',
      settings: {
        foreground: '#ffa657',
      },
    },
    {
      scope: ['markup.heading', 'markup.heading entity.name'],
      settings: {
        fontStyle: 'bold',
        foreground: '#64AFB5',
      },
    },
    {
      scope: 'markup.quote',
      settings: {
        foreground: '#7ee787',
      },
    },
    {
      scope: 'markup.italic',
      settings: {
        fontStyle: 'italic',
        foreground: '#FAF9F0',
      },
    },
    {
      scope: 'markup.bold',
      settings: {
        fontStyle: 'bold',
        foreground: '#FAF9F0',
      },
    },
    {
      scope: ['markup.underline'],
      settings: {
        fontStyle: 'underline',
      },
    },
    {
      scope: ['markup.strikethrough'],
      settings: {
        fontStyle: 'strikethrough',
      },
    },
    {
      scope: 'markup.inline.raw',
      settings: {
        foreground: '#64AFB5',
      },
    },
    {
      scope: [
        'markup.deleted',
        'meta.diff.header.from-file',
        'punctuation.definition.deleted',
      ],
      settings: {
        background: '#490202',
        foreground: '#774625',
      },
    },
    {
      scope: ['punctuation.section.embedded'],
      settings: {
        foreground: '#E8A23D',
      },
    },
    {
      scope: [
        'markup.inserted',
        'meta.diff.header.to-file',
        'punctuation.definition.inserted',
      ],
      settings: {
        background: '#04260f',
        foreground: '#7ee787',
      },
    },
    {
      scope: ['markup.changed', 'punctuation.definition.changed'],
      settings: {
        background: '#5a1e02',
        foreground: '#ffa657',
      },
    },
    {
      scope: ['markup.ignored', 'markup.untracked'],
      settings: {
        background: '#64AFB5',
        foreground: '#5E5C5A',
      },
    },
    {
      scope: 'meta.diff.range',
      settings: {
        fontStyle: 'bold',
        foreground: '#F6D1B8',
      },
    },
    {
      scope: 'meta.diff.header',
      settings: {
        foreground: '#64AFB5',
      },
    },
    {
      scope: 'meta.separator',
      settings: {
        fontStyle: 'bold',
        foreground: '#64AFB5',
      },
    },
    {
      scope: 'meta.output',
      settings: {
        foreground: '#64AFB5',
      },
    },
    {
      scope: [
        'brackethighlighter.tag',
        'brackethighlighter.curly',
        'brackethighlighter.round',
        'brackethighlighter.square',
        'brackethighlighter.angle',
        'brackethighlighter.quote',
      ],
      settings: {
        foreground: '#A4A3A1',
      },
    },
    {
      scope: 'brackethighlighter.unmatched',
      settings: {
        foreground: '#774625',
      },
    },
    {
      scope: ['constant.other.reference.link', 'string.other.link'],
      settings: {
        foreground: '#9ECFD7',
      },
    },
  ],
};
