/* eslint-disable @typescript-eslint/no-explicit-any */
/* eslint-disable @typescript-eslint/no-non-null-assertion */
/* eslint-disable @angular-eslint/component-selector */
import {
  ApplicationRef,
  Component,
  computed,
  EmbeddedViewRef,
  inject,
  input,
  TemplateRef,
  ViewContainerRef,
} from '@angular/core';
import { NgComponentOutlet, NgTemplateOutlet } from '@angular/common';
import {
  getTagNameRegistry,
  UiAssistantMessage,
  UiChatSchemaComponent,
} from '../utils';

/**
 * Renders messages generated by the assistant from uiChatResource.
 *
 * @public
 * @example
 *
 * ```html
 * <hb-render-message [message]="message" />
 * ```
 */
@Component({
  selector: 'hb-render-message',
  imports: [NgComponentOutlet, NgTemplateOutlet],
  template: `
    <ng-template #nodeTemplateRef let-node="node">
      <ng-template #childrenTemplateRef>
        @if (isTextNode(node)) {
          {{ node.$children }}
        } @else {
          @for (child of node.$children; track $index) {
            <ng-container
              *ngTemplateOutlet="nodeTemplateRef; context: { node: child }"
            />
          }
        }
      </ng-template>

      @if (node) {
        <ng-container
          *ngComponentOutlet="
            getTagComponent(node.$tag);
            inputs: node.$props;
            content: getRootNodes(childrenTemplateRef)
          "
        ></ng-container>
      }
    </ng-template>

    @if (content()) {
      @for (node of content(); track $index) {
        <ng-template
          [ngTemplateOutlet]="nodeTemplateRef"
          [ngTemplateOutletContext]="node"
        >
        </ng-template>
        <ng-container
          *ngTemplateOutlet="nodeTemplateRef; context: { node: node }"
        />
      }
    }
  `,
})
export class RenderMessageComponent {
  message = input.required<UiAssistantMessage<any>>();
  /**
   * @internal
   */
  appRef = inject(ApplicationRef);

  /**
   * @internal
   */
  content = computed(() => this.message().content?.ui ?? []);

  /**
   * @internal
   */
  tagNameRegistry = computed(() => getTagNameRegistry(this.message()));

  /**
   * @internal
   */
  viewContainerRef = inject(ViewContainerRef);

  /**
   * @internal
   */
  rootNodesWeakMap = new WeakMap<TemplateRef<any>, any[]>();

  /**
   * @internal
   */
  embeddedViewsWeakMap = new WeakMap<TemplateRef<any>, EmbeddedViewRef<any>>();

  /**
   * @internal
   */
  getTagComponent(tagName: string) {
    return this.tagNameRegistry()?.[tagName]?.component ?? null;
  }

  /**
   * @internal
   */
  getEmbeddedView(tpl: TemplateRef<any>) {
    if (this.embeddedViewsWeakMap.has(tpl)) {
      return this.embeddedViewsWeakMap.get(tpl)!;
    }

    const view = this.viewContainerRef.createEmbeddedView(tpl);
    this.embeddedViewsWeakMap.set(tpl, view);
    return view;
  }

  /**
   * @internal
   */
  getRootNodes(tpl: TemplateRef<any>) {
    if (this.rootNodesWeakMap.has(tpl)) {
      return this.rootNodesWeakMap.get(tpl)!;
    }

    const view = this.getEmbeddedView(tpl);
    const nodes = [view.rootNodes];
    this.rootNodesWeakMap.set(tpl, nodes);
    return nodes;
  }

  /**
   * @internal
   */
  isTextNode(node: UiChatSchemaComponent) {
    return typeof node.$children === 'string';
  }
}
